FROM python:3.9-bullseye

WORKDIR /app
COPY ./app /app/app
COPY ./requirements.txt .env* /app/
COPY ./entrypoint.sh /app/entrypoint.sh
COPY ./vue_dev /app/vue_dev

RUN chmod +x ./entrypoint.sh
# Installs node and npm for automatic vue build and mounting process
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm@latest && \
    npm cache clean --force

RUN python3.9 -m pip install --use-pep517 --no-cache-dir --upgrade -r /app/requirements.txt
# Vue build + mount executable
ENTRYPOINT ["./entrypoint.sh"]
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers", "--forwarded-allow-ips", "*"]